name: Deploying website on production environment

on:
  push:
    branches: [ feature/ci-cd ]

jobs:
  deploy_on_production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_ENV_IP }}
          username: ${{ secrets.PROD_ENV_USER }}
          port: ${{ secrets.PROD_ENV_PORT }}
          key: ${{ secrets.PROD_ENV_PRIVATE_KEY }}
          script: ${{ secrets.PROD_ENV_EXECUTION_SCRIPT }}


